import { DiagramGraph, UniversalType, TableDefinition } from '../types/schema';

export function mapTypeToBson(type: UniversalType): string {
  switch (type) {
    case 'int':
      return 'int';
    case 'bigint':
      return 'long';
    case 'float':
    case 'decimal':
      return 'double';
    case 'boolean':
      return 'bool';
    case 'varchar':
    case 'text':
    case 'uuid':
      return 'string';
    case 'date':
    case 'timestamp':
      return 'date';
    case 'json':
      return 'object';
    case 'blob':
      return 'binData';
    default:
      return 'string';
  }
}

export function compileMongo(graph: DiagramGraph): { code: string; errors: string[] } {
  const errors: string[] = [];
  const lines: string[] = [
    '// MongoDB Collection Definitions & JSON Schema Validators',
    '// Generated by eSQLer at ' + new Date().toISOString(),
    '// Execute these in mongosh or MongoDB Compass script runner',
    '',
  ];

  const tableMap = new Map<string, TableDefinition>();
  graph.tables.forEach((t) => tableMap.set(t.id, t));

  for (const table of graph.tables) {
    const requiredFields: string[] = [];
    const properties: Record<string, any> = {};

    table.columns.forEach((col) => {
      if (!col.isNullable) {
        requiredFields.push(col.name);
      }

      properties[col.name] = {
        bsonType: mapTypeToBson(col.type),
        description: col.comment || `Field ${col.name} of type ${col.type}`,
      };

      if (col.isPrimary) {
        properties[col.name].description += ' (Primary Identifier)';
      }
    });

    // Check relationships for this table
    const outgoingRels = graph.relationships.filter((r) => r.sourceTableId === table.id);
    outgoingRels.forEach((rel) => {
      const targetTable = tableMap.get(rel.targetTableId);
      const isEmbedded = rel.mongoStrategy === 'embedded';

      if (targetTable) {
        if (isEmbedded) {
          properties[`embedded_${targetTable.name}`] = {
            bsonType: rel.cardinality === '1:1' ? 'object' : 'array',
            description: `Embedded document(s) from ${targetTable.name} (Embedded Strategy)`,
          };
        } else {
          const sourceCol = table.columns.find((c) => c.id === rel.sourceColumnId);
          if (sourceCol) {
            properties[sourceCol.name].description += ` -> References ${targetTable.name}._id (Reference Strategy)`;
          }
        }
      }
    });

    const schemaValidator = {
      $jsonSchema: {
        bsonType: 'object',
        required: requiredFields.length > 0 ? requiredFields : undefined,
        properties,
      },
    };

    lines.push(`// Collection: ${table.name}`);
    lines.push(`db.createCollection('${table.name}', {`);
    lines.push(`  validator: ${JSON.stringify(schemaValidator, null, 2)}`);
    lines.push('});');
    lines.push('');

    // Add unique indexes
    const uniqueCols = table.columns.filter((c) => c.isUnique && !c.isPrimary);
    uniqueCols.forEach((c) => {
      lines.push(`db.${table.name}.createIndex({ '${c.name}': 1 }, { unique: true });`);
    });

    if (uniqueCols.length > 0) lines.push('');
  }

  return {
    code: lines.join('\n'),
    errors,
  };
}
